#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WarhammerCalculator.Resource", IsApplication=true)]

namespace WarhammerCalculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int difficulty_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int favicon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int mainLinear = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int spinner_dd_items = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int spinner_item = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int diff_text = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int difficulty = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int idtxtResult = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int rb_shoot_0 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int rb_shoot_1 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int rb_shoot_2 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int rb_shoot_3 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int rb_shoot_4 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int rb_shotmode_0 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int rb_shotmode_1 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int rb_shotmode_2 = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int result_error = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int result_failure = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int result_success = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int roll = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int show_result = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
